# see the .env file to set the variables used here
version: "2"
services:
  erddap:
    image: ${ERDDAP_DOCKER_IMAGE:-axiom/docker-erddap:2.22-jdk17-openjdk}
    restart: always
    container_name: ${CONTAINER_NAME:-erddap}
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-8090}:8080"
    volumes:
      - "./erddap/conf/robots.txt:/usr/local/tomcat/webapps/ROOT/robots.txt"
      - "./erddap/content:/usr/local/tomcat/content/erddap"
      - "./erddap/data:/erddapData"
      - "${DATASETS_DIR:-./datasets}:/datasets"
      - "/tmp/:/usr/local/tomcat/temp/"
      - "./datasets.d:/datasets.d:ro"
      - "./init.d:/init.d"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/erddap/index.html"
        ]
      interval: 10s
