name: Dataset Issue Report
description: File a bug report regarding a specific ERDDAP Dataset
title: '[Issue]: datasetID - ...'
labels: ['issue']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: dropdown
    id: issue_level
    attributes:
      label: Level
      description: Issue Level
      options:
        - High
        - Mid
        - Low
        - Future
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the issue related to this datasetID and potentially add an erddap link that highlights the issue.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: issue-solution
    attributes:
      label: Issue Solution
      description: Let us know if you have a solution.
      placeholder: The issue can be resolved by ....
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Relevant extra information (log output,etc.)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
