# Simple workflow for deploying static content to GitHub Pages
name: Caprover Deploy
run-name: Caprover Deploy ${{github.ref}}
on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - master
      - development
      - caprover-*
    paths:
      - .github/workflows/deploy-to-caprover.yaml
      - Dockerfile
      - erddap
  workflow_dispatch:
    
jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Compress repo to a tar file step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: .
          files: .
          outPath: packaged.tar
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Caprover CLI
        run: npm install -g caprover
      - name: Deploy ${{ github.ref_name }} on ${{ secrets.CAPROVER_APP_NAME }}
        run: |
          caprover deploy 
          --caproverUrl ${{ secrets.CAPROVER_URL }} 
          --appToken ${{ secrets.CAPROVER_TOKEN }} 
          --appName ${{ secrets.CAPROVER_APP_NAME }}
          --tarFile packaged.tar
