# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - master
      - development
    paths:
      - .github/workflows/deploy-to-caprover.yaml
      - Dockerfile

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # Single deploy job since we're just deploying
  deploy-production:
    if: github.ref == 'refs/heads/master'
    environment:
      name: production
      url: https://hakai-erddap.server.hakai.app/
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Caprover CLI
        run: npm install -g caprover
      - name: Tell Caprover server to deploy main
        run: caprover deploy --caproverUrl https://captain.server.hakai.app --appToken ${{ secrets.CAPROVER_TOKEN_MAIN }} --branch 'master' --appName hakai-ctd-map
  deploy-development:
    if: github.ref == 'refs/heads/development'
    environment:
      name: development
      url: https://hakai-eddap-dev.server.hak4i.org/
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Caprover CLI
        run: npm install -g caprover
      - name: Tell Caprover server to deploy development
        run: caprover deploy --caproverUrl https://captain.server.hak4i.org --appToken ${{ secrets.CAPROVER_TOKEN_DEVELOPMENT }} --branch 'development' --appName hakai-erddap-dev
      