name: Test on repository
run-name: Test ${{ github.ref_name }}
on:
  pull_request:
    branches:
      - master
      - development
      - caprover-deploy
    paths:
      - datasets.d/**
      - views/**
      - .github/workflows/review-datasets.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          VALIDATE_XML: true
          VALIDATE_SQL: true
          VALIDATE_SHELL_SHFMT: true
          LOG_LEVEL: WARN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run erddap_deploy test
        uses: hakaiinstitute/erddap-deploy/actions/test@main
        with:
          datasets_xml: datasets.d/**/*.xml
