name: Update ERDDAP server
on:
  push:
    branches:
      - master
      - development
  workflow_run:
    workflows: [Test datasets.xml and linter]
    types:
      - completed
jobs:
  development-update:
    name: Update ERDDAP
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          VALIDATE_XML: true
          VALIDATE_SQL: true
          VALIDATE_SHELL_SHFMT: true
          LOG_LEVEL: WARN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Review dataset.d/*.xml file names = datasetIDs
        run: sh .github/workflows/test-datasets.d.sh
      - name: Update development server
        if: github.ref_name == 'development'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          passphrase: ${{ secrets.DEV_SERVER_PASSPHRASE }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: cd  ~/hakai-datasets/; bash update-erddap.sh --hardFlag
      - name: Update production server
        if: github.ref_name == 'master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          passphrase: ${{ secrets.PROD_SERVER_PASSPHRASE }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: cd  ~/hakai-datasets/; bash update-erddap.sh --hardFlag
